services:
  - type: web
    name: jee-prep-web
    env: node
    plan: free
    rootDir: apps/web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
